import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>nextjs template</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className='grid h-screen place-items-center bg-zinc-900 text-white'>
                <h1 className='text-2xl'>Hello, World!</h1>
            </main>
        </>
    );
};

export default Home;
